### ISSUE TITLE
torus.login() hangs after selecting Google account on Safari 

### ISSUE THREAD

**Issue by miguelmota** [torusresearch/torus-embed#27] opened 2019-08-28 22:05 UTC
**Describe the bug**
On Safari, torus hangs after attempting to login with a Google account. Invoking torus.login() prompts the user to select the account, but after selection the torus.login() promise never resolves.

**To Reproduce**

```js
const Torus = require('@toruslabs/torus-embed').default

;(async () => {
  const login = document.querySelector('#login')
  const torus = new Torus()
  await torus.init()

  login.addEventListener('click', async event => {
    event.preventDefault()
    await torus.login()
    alert('done')
  })
})();
````

**Expected behavior**
Success response back after logging (like in Chrome)

**Screenshots**

Screencast shows that it works in Chrome, but hangs in Safari.

![m5lZfoFKqk](https://user-images.githubusercontent.com/168240/63895764-f5f7fb80-c9a4-11e9-85a3-fd43ae7cb088.gif)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser Safari
 - Version 12

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 12.4
 - Browser Safari
 - Version 

**Additional context**

Using torus-embed 0.0.28

**Comment by chaitanyapotti** [comment] 2019-09-04 10:22
@miguelmota We are unable to reproduce this issue.
Can we get on telegram to resolve this.?

**Comment by miguelmota** [comment] 2019-09-04 15:30
@chaitanyapotti my telegram handle is _@miguelmotah_

**Comment by miguelmota** [comment] 2019-09-08 20:01
Exact steps to reproduce:

1. `npm i @toruslabs/torus-embed@0.0.28`

1. `index.js`

```js
const Torus = require('@toruslabs/torus-embed').default

;(async () => {
  const login = document.querySelector('#login')
  const torus = new Torus()
  window.torus = torus

  await torus.init()

  login.addEventListener('click', async event => {
    event.preventDefault()
    await torus.login()
    alert('done')
  })
})();
```

1. `browserify index.js -o bundle.js`

1. `index.html`

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=yes">
  <title></title>
</head>
<body>
  <button id="login">login</button>
  <script src="bundle.js"></script>
</body>
</html>
```

1. `python -m http.server 3000`

1. open http://localhost:3000

1. click the login button

1. select google account, popup will close after this

1. notice that the alert never gets triggered

<img width="396" alt="Screen Shot 2019-09-08 at 1 01 25 PM" src="https://user-images.githubusercontent.com/168240/64493736-cbc1fb80-d238-11e9-833f-5f2fe1950811.png">

**Comment by chaitanyapotti** [comment] 2019-09-18 05:41
I used the exact same settings and same browser as well. I still couldn't replicate the error

**Comment by miguelmota** [comment] 2019-09-18 05:48
Have you tried it on mobile Safari?

**Comment by chaitanyapotti** [comment] 2019-09-18 06:39
I'm able to replicate this on mobile safari. Looks like others are also facing similar [issue](https://github.com/google/google-api-javascript-client/issues/553).

The issue is with gapi client popup not being able to communicate back to the iframe it originated from in mobile safari.

**Comment by YZhenY** [comment] 2019-09-18 06:53
Being issue inherent with the Google OAuth gapi, theres not much we can do right now. We've opened an enquiry with them.

In the mean time, we're about to push multiple other logins into production. This includes fb, telegram, github and others. We can offer other logins to them for the time being.

**Comment by miguelmota** [comment] 2019-09-18 06:59
Feel free to close the issue since it's on Google's end. My main concern was the user using mobile Safari since we can direct them to different browsers on desktop but mobile iOS browsers are based on WebKit so others wouldn't work as well

@YZhenY cool! that's going to be awesome and solve many problems then

**Comment by chaitanyapotti** [comment] 2019-09-18 08:00
@miguelmota It works on ios chrome though.
closing with user's consent

**Closed by chaitanyapotti** 2019-09-18 08:00 UTC
Labels: question

**Comment by miguelmota** [comment] 2019-09-18 08:52
You're right it does work on Chrome. I remember trying it a while back and it didn't work but good to know
