### ISSUE TITLE
Connect with email on iPhone not working

### ISSUE THREAD

**Issue by petecgny** [torusresearch/torus-embed#399] opened 2021-12-21 21:17 UTC
**Describe the bug**
When I run my dAPP on my iPhone running IOS 15.1 in Safari and try to connect to my Torus Wallet using email, not social sign-in, it does not connect when I return to my app after clicking the verification email.  It works on mobile with social sign-in and it works on my laptop with email.

**To Reproduce**

**Expected behavior**
Expect to connect when I return to my Dapp in the browser.

**Screenshots**

If it would help let me know and I can record a video of my iPhone screen as I go through the steps to connect, verify my email, and go back to my dApp.

**Smartphone (please complete the following information):**
 - Device: iPhone10XR
 - OS: iOS 15.1]
 - Browser Safari

**Additional context**

**Comment by BboyStatix** [comment] 2021-12-24 03:58
Hey there @petecgny are you accessing your email via another app, or within the safari browser itself?

**Comment by petecgny** [comment] 2021-12-24 17:32
Hi @BboyStatix I access my email from the native email app on my iPhone.  When I click 'confirm my email' it opens up a tab in my safari browser that says Done.  Close this and return to your previous window.  When I do and go back to the safari tab my dApp is running in I am not connected.

**Comment by BboyStatix** [comment] 2021-12-29 09:05
Hi @petecgny we are currently working on resolving this issue. I've reproduced it internally and it seems to be related to IOS 15 Safari having the experimental "NSURLSession WebSocket" open by default. Turning that off seems to fix the issue (can be found in Settings > Safari > Advanced > Experimental Features). Of course this is only a temporary workaround.
Relevant link: https://developer.apple.com/forums/thread/685403

When clicking the magic link from outside Safari (e.g. Mail app), it seems to cause the WebSocket connection to terminate and initiates a new one. On the other hand if it were clicked from within Safari (e.g. another tab logged into your mailbox) the issue doesn't occur.

We'll continue working on a fix. For the time being you can use the above workarounds.

**Comment by petecgny** [comment] 2021-12-29 15:26
Thank you, Naveed.  Glad you were able to reproduce it and isolate what is
causing the problem.

**Comment by petecgny** [comment] 2022-01-06 14:49
Hi @chaitanyapotti, I see you marked this issue as closed.  @BboyStatix was able to reproduce and isolate the issue but did not come up with a fix yet.  Asking our customers to change their settings in order to connect their Torus wallet using email on an iPhone is not a good user experience or something we expect they will do.  

Are you working on a fix beyond this temporary solution and when do you expect to have it resolved?

**Comment by petecgny** [comment] 2022-01-17 14:46
@BboyStatix following up to see if you have a fix for this

**Comment by BboyStatix** [comment] 2022-01-18 04:30
@petecgny we are currently testing out a fix https://github.com/torusresearch/torus-passwordless-auth-frontend/pull/39

**Comment by BboyStatix** [comment] 2022-01-21 02:58
@petecgny can you try it out now?

**Comment by petecgny** [comment] 2022-01-21 12:58
@BboyStatix Awesome.  It worked.  Thank you. What was the fix and how hard was it to figure out?

**Comment by BboyStatix** [comment] 2022-01-23 03:29
@petecgny great to hear that.
This was the PR that fixed it https://github.com/torusresearch/torus-passwordless-auth-frontend/pull/41
Basically, upon socket reconnection, we re-request the server to emit the event the logs the user in. This solves the problem of us missing the emitted server event when the user minimises app (due to the websocket connection being closed).

**Closed** 2022-01-23 03:31 UTC
